[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["lib", "staticlib"]

[features]
log_gc = []
print_code = []
stress_gc = []
trace_execution = []

[dependencies]
libc = "0.2.150"
once_cell = "1.18.0"

[build-dependencies]
cbindgen = "0.26.0"
